# Generated by Django 5.2.5 on 2025-08-25 13:47

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('color', models.CharField(choices=[('bg-blue-500', 'Blue'), ('bg-green-500', 'Green'), ('bg-purple-500', 'Purple'), ('bg-red-500', 'Red'), ('bg-yellow-500', 'Yellow'), ('bg-indigo-500', 'Indigo'), ('bg-pink-500', 'Pink'), ('bg-gray-500', 'Gray')], default='bg-blue-500', max_length=20)),
                ('alert_threshold', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('email_alerts', models.BooleanField(default=True)),
                ('sms_alerts', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('threshold', 'Threshold Reached'), ('exceeded', 'Budget Exceeded'), ('period_end', 'Period Ending')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budgets.budget')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('performance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='budgets.budget')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='BudgetTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('color', models.CharField(choices=[('bg-blue-500', 'Blue'), ('bg-green-500', 'Green'), ('bg-purple-500', 'Purple'), ('bg-red-500', 'Red'), ('bg-yellow-500', 'Yellow'), ('bg-indigo-500', 'Indigo'), ('bg-pink-500', 'Pink'), ('bg-gray-500', 'Gray')], default='bg-blue-500', max_length=20)),
                ('alert_threshold', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budgets.budgettemplate')),
            ],
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'status'], name='budgets_bud_user_id_60f731_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['period_start', 'period_end'], name='budgets_bud_period__09f043_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'status')},
        ),
        migrations.AddIndex(
            model_name='budgetalert',
            index=models.Index(fields=['budget', 'is_read'], name='budgets_bud_budget__021b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetalert',
            index=models.Index(fields=['created_at'], name='budgets_bud_created_ae3ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='budgethistory',
            index=models.Index(fields=['budget', 'period_start'], name='budgets_bud_budget__7e35cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgettemplateitem',
            unique_together={('template', 'category')},
        ),
    ]
