# Generated by Django 5.2.5 on 2025-09-27 06:49

import django.db.models.deletion
from django.db import migrations, models
import uuid


def map_category_names_to_fk(apps, schema_editor):
    Budget = apps.get_model('budgets', 'Budget')
    Category = apps.get_model('transactions', 'Category')

    for budget in Budget.objects.all():
        # Only process if category is still stored as a string
        if isinstance(budget.category, str):
            category_obj, _ = Category.objects.get_or_create(
                name=budget.category,
                defaults={"id": uuid.uuid4()}  # only if Category uses UUID as PK
            )
            budget.category = category_obj.id
            budget.save(update_fields=["category"])


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_alter_budget_category'),
        ('transactions', '0006_transaction_category_and_more'),
    ]

    operations = [
        # Map string categories -> FK categories
        migrations.RunPython(map_category_names_to_fk),

        # Remove old FK field if it existed
        migrations.RemoveField(
            model_name='budget',
            name='category_fk',
        ),

        # Convert category field into a ForeignKey
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='budgets',
                to='transactions.category',
            ),
        ),

        # Remove the duplicate Category model from budgets app
        migrations.DeleteModel(
            name='Category',
        ),
    ]
