# Generated by Django 5.2.5 on 2025-08-31 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_transaction_user_id_98a6b3_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_user_id_a385c1_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
