# Generated by Django 5.2.5 on 2025-09-27 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Kenyan phone number format', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+254712345678' or '0712345678'", regex='^(?:\\+254\\d{9}|0\\d{9})$')]),
        ),
    ]
